I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/prologue2.rpy", line 735, in script call
    call screen investigation(0,0)
  File "game/misc.rpy", line 54, in script call
    call screen hisakoRoom()
  File "game/chapters/prologue2.rpy", line 747, in script
    hkmonologue "I promise not only to the school and the government, but also to myself that I will put 110% into everything I do here!"
TypeError: %i format: a number is required, not TagQuotingDict

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/prologue2.rpy", line 735, in script call
    call screen investigation(0,0)
  File "game/misc.rpy", line 54, in script call
    call screen hisakoRoom()
  File "game/chapters/prologue2.rpy", line 747, in script
    hkmonologue "I promise not only to the school and the government, but also to myself that I will put 110% into everything I do here!"
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\exports.py", line 1483, in say
    what = what % tag_quoting_dict
TypeError: %i format: a number is required, not TagQuotingDict

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Reawakening 1.0
Sun Jul 14 21:19:55 2024
